name:                depsolver
version:             0.1.0.0
github:              "githubuser/depsolver"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/depsolver#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -O2
  - +RTS -H512m -K512m -RTS
  dependencies:
  - text
  - aeson
  - bytestring
  - unordered-containers
  - vector
  - containers
  - filepath
  - process
  - time

executables:
  solve:
    main:                Main.hs
    ghc-options:
    - -O2
    - +RTS -H512m -K512m -RTS
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - depsolver
    - bytestring


# tests:
#   depsolver-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - depsolver
